site_name: FungiTastic
repo_url: https://github.com/bohemianvra/FungiTastic/
repo_name: FungiTastic

theme:
  name: material
  palette:
    scheme: slate
    primary: brown
    accent: lime

markdown_extensions:
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

plugins:
  - search
  - redirects

extra_javascript:
  - javascripts/nav-click.js

nav:
  - Introduction: index.md
  - Dataset Overview:
      - Available Data, Subsets & Splits: dataset.md
      - Metadata: data/metadata.md
      - Captions: data/captions.md
      - Satellite Images: data/satellite.md
      - Segmentation Masks: data/masks.md
      - Climate Time Series: data/climate.md
  - Benchmarks:
      - Overview: benchmarks.md
      - FungiCLEF 2025: benchmarks/FungiCLEF2025.md
      - Closed-set Classification: benchmarks/closed.md
      - Open-set Classification: benchmarks/open.md
      - Few-shot Learning: benchmarks/few_shot.md
      - Chronological Shift: benchmarks/chronological.md
      - Cost-sensitive Classification: benchmarks/cost_sensitive.md
      - Segmentation Task: benchmarks/segmentation.md
  - Baselines & Tutorials:
      - Overview: baselines_and_models.md
      - Training Your Model: usage/training.md
      # - Evaluation Protocols: usage/evaluation.md Separately in each Benchmark
      - Closed-set Models: baselines_and_models/closed.md
      - Few-shot Models: baselines_and_models/few_shot.md
      - Open-set Models: baselines_and_models/open.md
      - VLM Fusion: baselines_and_models/vlm.md
  - Download: download.md
  - Citation & Acknowledgements: citation.md
