# data
augmentations: "vit_heavy"
image_size: [224, 224]
dataset: "FungiTastic"

# model
architecture: "resnet18.a1_in1k"

# training
train:
loss: "CrossEntropyLoss"
optimizer: "SGD"
scheduler: "plateau"
epochs: 100
learning_rate: 0.01
batch_size: 64
accumulation_steps: 1

# other
random_seed: 777
workers: 8
multigpu: False
tags: ["FungiTastic-CloseSet", "224x224"]
root_path: "../"