num_workers: 4
split: 'test'

# other
random_seed: 777
root_path: "../../../"
path_out: "../../../out/"
debug: False

data_path: 'path_to_FungiTastic'
mask_path: 'path_to_masks'
# models will be downloaded to this path
ckpt_path: 'path_to_model_ckpts'