num_workers: 4
split: 'val'

# other
random_seed: 777
root_path: "./"
path_out: "out/"
debug: False

data_path: '/mnt/vrg2/imdec/datasets/FungiTastic'
mask_path: "out/"
# models will be downloaded to this path
ckpt_path: "ckpts/"